<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Avtomagazin.ApiClient\Avtomagazin.ApiClient.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Avtomagazin.Contracts\Avtomagazin.Contracts.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Avtomagazin.ServiceDefaults\Avtomagazin.ServiceDefaults.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
